apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fintech
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: ClusterIP    # Internal only - ALB Ingress routes external traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
