apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fintech
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000    # Routes to port 3000 in the container (server.js)
